import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container: { padding: 16, paddingBottom: 40 },
    backButton: { marginBottom: 10 },
    stepText: { color: "#777", fontSize: 14, marginBottom: 6 },
    title: { fontSize: 22, fontWeight: "600", marginBottom: 20 },
    sectionTitle: { fontSize: 18, fontWeight: "600", marginBottom: 12, marginTop: 12 },
    summaryItem: { marginBottom: 14 },
    summaryLabel: { color: "#777", fontSize: 14 },
    summaryValue: { fontSize: 16, fontWeight: "500", marginTop: 4 },
    walletCard: {
        borderWidth: 1,
        borderColor: "#E60023",
        borderRadius: 12,
        padding: 14,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    walletTitle: { fontSize: 16, fontWeight: "600" },
    walletSubtitle: { color: "#777", fontSize: 13 },
    radioOuter: {
        width: 20,
        height: 20,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: "#aaa",
        justifyContent: "center",
        alignItems: "center",
    },
    radioOuterActive: { borderColor: "#E60023" },
    radioInner: { width: 10, height: 10, borderRadius: 6, backgroundColor: "#E60023" },
    summaryRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6 },
    summaryLeft: { color: "#555", fontSize: 15 },
    summaryRight: { fontSize: 15, fontWeight: "600" },
    infoText: { fontSize: 13, color: "#777", marginTop: 10 },
    submitButton: {
        backgroundColor: "#E60023",
        paddingVertical: 16,
        borderRadius: 30,
        marginTop: 30,
    },
    submitText: { color: "#fff", fontSize: 17, textAlign: "center", fontWeight: "600" },
});