import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    header: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: "700",
        color: "#000",
    },
    scrollContainer: {
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 100,
    },
    card: {
        backgroundColor: "#fff",
        padding: 16,
        marginBottom: 12,
        borderRadius: 12,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 3 },
        elevation: 2,
        borderWidth: 1,
        borderColor: "#eee",
    },
    userRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#ddd",
        marginRight: 12,
    },
    name: { fontWeight: "600", fontSize: 16, color: "#000" },
    subText: { color: "#888", fontSize: 13 },
    description: { color: "#444", fontSize: 14, marginBottom: 8 },
    locationText: { fontSize: 13, color: "#666" },
    locationLink: { color: "#007AFF", fontWeight: "500" },

    sectionHeader: {
        backgroundColor: "#F6F7FB",
        padding: 8,
        borderRadius: 6,
        marginBottom: 10,
    },
    sectionHeaderText: {
        color: "#6C6C6C",
        fontWeight: "600",
        fontSize: 14,
    },
    sectionHeaderActive: {
        backgroundColor: "#FF3B30",
        padding: 8,
        borderRadius: 6,
        marginTop: 20,
    },
    sectionHeaderActiveText: {
        color: "#fff",
        fontWeight: "700",
        fontSize: 14,
    },
    sectionHeaderCompleted: {
        backgroundColor: "#E9E9E9",
        padding: 8,
        borderRadius: 6,
        marginTop: 20,
    },
    sectionHeaderCompletedText: {
        color: "#8A8A8A",
        fontWeight: "600",
    },
    lightCard: {
        backgroundColor: "#fff",
        borderRadius: 10,
        padding: 14,
        borderWidth: 1,
        borderColor: "#eee",
        marginBottom: 16,
    },
    activeCard: {
        backgroundColor: "#fff",
        borderRadius: 10,
        padding: 14,
        marginTop: 10,
        borderWidth: 1,
        borderColor: "#FF3B30",
    },
    completedCard: {
        backgroundColor: "#f9f9f9",
        borderRadius: 10,
        padding: 14,
        borderWidth: 1,
        borderColor: "#ddd",
        opacity: 0.9,
        marginTop: 10,
    },
    cardTitle: { fontSize: 15, fontWeight: "600", marginBottom: 4 },
    cardDescription: { color: "#555", fontSize: 13 },
    viewButton: {
        backgroundColor: "#FF3B30",
        paddingVertical: 8,
        borderRadius: 6,
        alignItems: "center",
        marginTop: 10,
    },
    viewButtonText: { color: "#fff", fontWeight: "600" },
    fab: {
        position: "absolute",
        bottom: 25,
        right: 25,
        backgroundColor: "#000",
        width: 54,
        height: 54,
        borderRadius: 27,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#333",
        marginTop: 10,
    },
    emptyText: { fontSize: 14, color: "#888", marginTop: 4 },
});
